### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by wang-na** [kirralabs/indonesian-fenom#1]
Hi,
I'm very happy to find your indonesian-fonem project here.
However, unluckly, I can't open the source website:http://semangatkecil.blogspot.com/2018/09/menelisik-komponen-kebahasaan-untuk.html
If it's convinient for you, can you share script with us?
We're now doing research on Indonesian grapheme to phoneme converting project.
Thank you very much for sharing!
Looking forward to your reply~

**Comment by ardhimaarik** [comment]
Hi @wang-na, nice to know you're working on Indonesian SR projects. 
as far as i know, the script is available on internet and you can find it easily. 
the important things is base data we are using. 

you can findout my projects here, related to g2p. i used common tools for this project. (i not using this tools for my real project, with bigger data)
https://github.com/ardhimaarik/lexiconBIndo

if you want to get higher accuracy you can add more data to datasets.
but, i can't shared more datasets for now.

**Comment by ardhimaarik** [comment]
i will close it. you can create another issue if needed
